# Generated by Django 5.2.8 on 2025-12-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.ImageField(blank=True, null=True, upload_to='movies/'),
        ),
    ]
